#line 2 "khroK.c"

#line 4 "khroK.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer kk_create_buffer
#define yy_delete_buffer kk_delete_buffer
#define yy_flex_debug kk_flex_debug
#define yy_init_buffer kk_init_buffer
#define yy_flush_buffer kk_flush_buffer
#define yy_load_buffer_state kk_load_buffer_state
#define yy_switch_to_buffer kk_switch_to_buffer
#define yyin kkin
#define yyleng kkleng
#define yylex kklex
#define yylineno kklineno
#define yyout kkout
#define yyrestart kkrestart
#define yytext kktext
#define yywrap kkwrap
#define yyalloc kkalloc
#define yyrealloc kkrealloc
#define yyfree kkfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE kkrestart(kkin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int kkleng;

extern FILE *kkin, *kkout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up kktext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up kktext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via kkrestart()), so that the user can continue scanning by
	 * just pointing kkin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when kktext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int kkleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow kkwrap()'s to do buffer switches
 * instead of setting up a fresh kkin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void kkrestart (FILE *input_file  );
void kk_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE kk_create_buffer (FILE *file,int size  );
void kk_delete_buffer (YY_BUFFER_STATE b  );
void kk_flush_buffer (YY_BUFFER_STATE b  );
void kkpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void kkpop_buffer_state (void );

static void kkensure_buffer_stack (void );
static void kk_load_buffer_state (void );
static void kk_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER kk_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE kk_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE kk_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE kk_scan_bytes (yyconst char *bytes,int len  );

void *kkalloc (yy_size_t  );
void *kkrealloc (void *,yy_size_t  );
void kkfree (void *  );

#define yy_new_buffer kk_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        kkensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            kk_create_buffer(kkin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        kkensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            kk_create_buffer(kkin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define kkwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *kkin = NULL, *kkout = NULL;

typedef int yy_state_type;

extern int kklineno;

int kklineno = 1;

extern char *kktext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr kktext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up kktext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	kkleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[294] =
    {   0,
        0,    0,  131,  130,    1,  130,  130,  130,  130,  130,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   64,   65,   66,   67,    0,    7,   48,
       13,    0,   16,   19,   27,   31,   33,   34,   38,   42,
        0,    0,    0,    0,    0,    0,  110,   74,   75,   77,
       78,    0,    0,    0,   49,   50,   51,   52,   53,    0,
       55,   56,   58,   59,   60,   61,   62,   63,    0,    0,
        0,    0,    2,    0,    0,    0,    0,    0,   14,    0,
        0,    0,    0,    0,    0,    0,   26,    0,    0,    0,
       34,    0,   34,    0,    0,    0,    0,    0,  119,  120,

      115,  121,  122,  123,  124,  125,   36,   80,   79,   81,
       82,   83,   84,   86,  113,  109,  116,   72,    0,   88,
      126,  127,  128,  129,    0,    0,   43,   90,   97,  102,
      103,  104,  106,  107,   87,  111,  112,  108,  117,   73,
       68,   69,   70,  118,   71,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       29,    0,    0,    0,    0,    0,   35,    0,    0,    0,
       40,    0,    0,   11,    0,    0,  114,    0,   37,    0,
        0,   85,   85,    0,    0,    0,    0,    0,    0,    0,
        0,   45,    0,    4,    5,    6,    6,    8,    9,   12,

       15,   15,   17,   18,   18,   18,    0,   26,   29,   29,
       29,    0,   34,   35,   39,   40,   11,   11,   10,   10,
        0,    0,    0,    0,   46,   54,   91,    0,    0,    0,
        0,    0,    0,    0,    3,    6,   18,   18,    0,    0,
        0,    0,    0,   76,   76,    0,    0,    0,    0,    0,
        0,    0,  105,   41,   21,    0,   25,   18,    0,    0,
        0,   89,   94,   98,    0,   96,   93,   95,    0,  101,
       99,    0,    0,   18,    0,   30,   28,    0,    0,  100,
        0,   24,   18,   23,    0,    0,   92,    0,    0,   22,
        0,   20,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    4,    1,    4,    4,    4,    4,    3,
        3,    4,    4,    4,    4,    4,    4,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,    4,    4,    4,
        4,    4,   15,    1,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        4,    1,    4,    4,    4,   17,   18,   19,   20,   21,

       16,   22,   16,   16,   23,   16,   16,   16,   16,   16,
       24,   16,   16,   25,   26,   16,   16,   27,   16,   16,
       16,   16,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[28] =
    {   0,
        1,    2,    2,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    2,    4,    2,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    5
    } ;

static yyconst flex_uint16_t yy_base[330] =
    {   0,
        0,   10,  322,  323,  323,   32,    2,  294,    4,   54,
       69,   79,  315,  313,  313,    0,   83,  311,  311,   89,
       99,  310,    6,  323,  323,  323,  323,  309,   17,   22,
        2,   24,  323,   25,   95,  323,  323,   46,  323,   26,
       47,  116,  306,  306,  124,    6,  323,  323,  293,  323,
      323,  305,  131,  285,  323,  323,  323,  323,  323,  284,
      323,  323,  323,  323,  323,  323,  323,  323,   43,  135,
      145,  150,  323,   93,  302,  279,  278,  277,  323,  276,
      275,  274,  273,  272,  271,   68,  323,  270,   31,  276,
      268,    0,  267,  266,   45,   59,    0,   88,  323,  323,

      149,  323,  323,  323,  323,  323,  150,  323,  323,  323,
      323,  274,  158,  323,  323,  323,  323,  323,  286,  323,
      323,  323,  323,  323,  263,  262,  323,  264,  145,  323,
      323,  269,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  268,  323,  323,    0,  280,    0,  276,  278,
        0,    0,    0,    0,    0,    0,    0,  277,  268,    0,
      253,    0,    0,    0,  274,    0,  323,    0,    0,    0,
      323,    0,    0,  323,    0,    0,  323,  272,  323,  250,
      270,  323,  323,  269,    0,    0,    0,  159,  268,  268,
      266,    0,  265,    0,  323,  164,    0,    0,  323,    0,

        0,    0,    0,    0,  169,    0,  248,  267,    0,    0,
        0,  158,    0,    0,    0,    0,    0,    0,    0,    0,
      259,  262,  261,  183,    0,    0,    0,  177,  260,  259,
      163,  257,  253,  259,  236,  257,  253,  239,  229,  231,
      248,  245,    0,  323,  323,  175,    0,    0,    0,  246,
      249,  176,  323,  323,  323,  244,  323,  243,  243,    0,
      236,  323,  323,  323,  170,  323,  323,  323,  244,  323,
      323,  239,  235,  234,  236,    0,  323,  236,  235,  323,
      230,  323,  220,    6,  231,  230,  323,  230,  219,  323,
      221,  323,  323,  203,  206,  229,  228,  211,  227,  226,

      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  207,  196,  193,  189,  188,  185,
      178,  177,  128,  102,   65,   52,   43,   28,    0
    } ;

static yyconst flex_int16_t yy_def[330] =
    {   0,
      294,  294,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,   42,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  295,  293,  293,
      293,  296,  293,  293,  293,  293,  297,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  298,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  299,  293,  300,  293,  301,
      302,  303,  304,  305,  306,  307,  308,  309,  293,  310,
      295,  311,  312,  313,  293,  314,  293,  315,  316,  317,
      293,  318,  319,  293,  320,  321,  293,  293,  293,  293,
      293,  293,  293,  293,  322,  323,  324,  293,  293,  293,
      293,  299,  293,  300,  293,  301,  301,  302,  293,  304,

      305,  306,  307,  308,  309,  309,  293,  310,  311,  312,
      313,  293,  314,  315,  316,  317,  318,  319,  320,  321,
      293,  293,  293,  293,  322,  323,  324,  293,  293,  293,
      293,  293,  293,  293,  301,  301,  309,  309,  293,  293,
      293,  293,  325,  293,  293,  293,  326,  327,  328,  293,
      293,  293,  293,  293,  293,  293,  293,  309,  293,  329,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  309,  293,  329,  293,  293,  293,  293,
      293,  293,  309,  293,  293,  293,  293,  293,  293,  293,
      293,  293,    0,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

static yyconst flex_uint16_t yy_nxt[351] =
    {   0,
      293,  293,  276,   79,   45,   46,   17,  289,   20,   21,
       70,   71,  115,  116,  117,  118,    5,    6,   73,   80,
      290,    7,    8,    9,   22,   10,    5,    6,   18,  268,
       23,    7,    8,    9,   74,   10,   11,   12,   75,   77,
       76,   81,   83,   94,  267,   78,   84,   82,   85,   95,
      293,  163,   13,  266,  127,   14,   15,  164,   16,   24,
       25,   26,   27,   91,   96,  170,  263,   92,   97,   93,
       98,  171,  159,   28,   29,   30,   31,   32,   33,  172,
       34,   35,   36,   37,   38,  173,   39,   40,  160,   41,
       47,   48,   49,   50,   51,   54,   55,   56,   57,   58,

       59,   60,   61,   62,  227,   63,   64,   65,  175,   66,
       67,   68,   86,  146,  176,   87,   88,  147,   89,  148,
       90,   99,  100,  101,  102,  103,  104,  105,  106,  109,
      226,  110,  111,  112,  113,  114,  121,  122,  123,  124,
      128,  129,  130,  131,  132,  133,  134,  135,  136,  137,
      177,  179,  138,  139,  140,  141,  142,  143,  144,  145,
      183,  183,  188,  228,  229,  240,  178,  180,  189,  251,
      235,  252,  183,  236,  183,  237,  264,  271,  238,  225,
      220,  241,  246,  230,  244,  245,  244,  219,  247,  248,
      218,  217,  265,  272,  278,  216,  279,  245,  215,  244,

      244,  244,  244,    4,    4,    4,    4,    4,  161,  214,
      161,  182,  182,  182,  213,  211,  210,  209,  208,  206,
      204,  203,  202,  201,  200,  199,  198,  197,  194,  192,
      174,  167,  292,  290,  291,  280,  264,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  277,  275,  274,  273,
      270,  269,  262,  261,  241,  260,  259,  258,  257,  256,
      255,  254,  253,  250,  249,  243,  242,  177,   87,  239,
      234,  233,  232,  231,  224,  223,  222,  221,  212,  293,
      207,  205,  196,  195,  193,  191,  190,  187,  186,  185,
      184,  181,  169,  168,  166,  165,  162,  158,  157,  156,

      155,  154,  153,  152,  151,  150,  149,  126,  125,  120,
      119,  108,  107,   72,   69,   53,   52,   44,   43,   42,
       19,  293,    3,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

static yyconst flex_int16_t yy_chk[351] =
    {   0,
        0,    0,  329,   31,   16,   16,    7,  284,    9,    9,
       23,   23,   46,   46,   46,   46,    1,    1,   29,   31,
      284,    1,    1,    1,    9,    1,    2,    2,    7,  328,
        9,    2,    2,    2,   29,    2,    6,    6,   29,   30,
       29,   32,   34,   40,  327,   30,   34,   32,   34,   40,
       69,   89,    6,  326,   69,    6,    6,   89,    6,   10,
       10,   10,   10,   38,   41,   95,  325,   38,   41,   38,
       41,   95,   86,   10,   11,   11,   11,   11,   11,   96,
       11,   11,   11,   12,   12,   96,   12,   12,   86,   12,
       17,   17,   17,   17,   17,   20,   20,   20,   20,   20,

       20,   20,   20,   21,  324,   21,   21,   21,   98,   21,
       21,   21,   35,   74,   98,   35,   35,   74,   35,   74,
       35,   42,   42,   42,   42,   42,   42,   42,   42,   45,
      323,   45,   45,   45,   45,   45,   53,   53,   53,   53,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   71,
      101,  107,   71,   71,   71,   72,   72,   72,   72,   72,
      113,  113,  129,  188,  188,  212,  101,  107,  129,  231,
      196,  231,  113,  196,  113,  205,  246,  252,  205,  322,
      321,  212,  228,  188,  224,  224,  224,  320,  228,  228,
      319,  318,  246,  252,  265,  317,  265,  224,  316,  224,

      224,  224,  224,  294,  294,  294,  294,  294,  295,  315,
      295,  298,  298,  298,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      297,  296,  291,  289,  288,  286,  285,  283,  281,  279,
      278,  275,  274,  273,  272,  269,  261,  259,  258,  256,
      251,  250,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  230,  229,  223,  222,  221,  208,  207,
      193,  191,  190,  189,  184,  181,  180,  178,  165,  161,
      159,  158,  150,  149,  147,  143,  132,  128,  126,  125,
      119,  112,   94,   93,   91,   90,   88,   85,   84,   83,

       82,   81,   80,   78,   77,   76,   75,   60,   54,   52,
       49,   44,   43,   28,   22,   19,   18,   15,   14,   13,
        8,    3,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int kk_flex_debug;
int kk_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *kktext;
#line 1 "khroK.l"
#line 651 "khroK.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int kklex_destroy (void );

int kkget_debug (void );

void kkset_debug (int debug_flag  );

YY_EXTRA_TYPE kkget_extra (void );

void kkset_extra (YY_EXTRA_TYPE user_defined  );

FILE *kkget_in (void );

void kkset_in  (FILE * _in_str  );

FILE *kkget_out (void );

void kkset_out  (FILE * _out_str  );

			int kkget_leng (void );

char *kkget_text (void );

int kkget_lineno (void );

void kkset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int kkwrap (void );
#else
extern int kkwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( kktext, (size_t) kkleng, 1, kkout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( kkin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( kkin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, kkin))==0 && ferror(kkin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(kkin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int kklex (void);

#define YY_DECL int kklex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after kktext and kkleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! kkin )
			kkin = stdin;

		if ( ! kkout )
			kkout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			kkensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				kk_create_buffer(kkin,YY_BUF_SIZE );
		}

		kk_load_buffer_state( );
		}

	{
#line 6 "khroK.l"

 /*[\n\t ' ']  {};
 /*asoundc*/
#line 873 "khroK.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of kktext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 294 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 323 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "khroK.l"
{printf("។");}
	YY_BREAK
case 2:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 10 "khroK.l"
{printf("ក");}
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 11 "khroK.l"
{printf("ក");}
	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 12 "khroK.l"
{printf("ក");}  
	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 13 "khroK.l"
{printf("គ");}
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 14 "khroK.l"
{printf("គ");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 "khroK.l"
{printf("ក");}
	YY_BREAK
case 8:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 16 "khroK.l"
{printf("ខ");}
	YY_BREAK
case 9:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 17 "khroK.l"
{printf("ឃ");}
	YY_BREAK
/*a03/ov[0-9]+            {printf("ជ");}     */ 
case 10:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 19 "khroK.l"
{printf("ជ");} 
	YY_BREAK
case 11:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 20 "khroK.l"
{printf("ច");}     
	YY_BREAK
case 12:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 21 "khroK.l"
{printf("ឆ");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 22 "khroK.l"
{printf("ឆ");}
	YY_BREAK
case 14:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 23 "khroK.l"
{printf("ច");}
	YY_BREAK
case 15:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 24 "khroK.l"
{printf("ឈ");}       
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "khroK.l"
{printf("ដ");}     
	YY_BREAK
case 17:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 26 "khroK.l"
{printf("ណ");}
	YY_BREAK
case 18:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 27 "khroK.l"
{printf("ន");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 28 "khroK.l"
{printf("ន");}
	YY_BREAK
case 20:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 29 "khroK.l"
{printf("ន");}
	YY_BREAK
/*special case*/
case 21:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 33 "khroK.l"
{printf("ការ");}
	YY_BREAK
case 22:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 34 "khroK.l"
{printf("នាក់");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "khroK.l"
{printf("អ្នក");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "khroK.l"
{printf("ក៏");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "khroK.l"
{printf("ក៏");}
	YY_BREAK
/*special case*/
case 26:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 41 "khroK.l"
{printf("ត");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "khroK.l"
{printf("ត");}
	YY_BREAK
case 28:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 43 "khroK.l"
{printf("ធ");}
	YY_BREAK
case 29:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 44 "khroK.l"
{printf("ទ");}
	YY_BREAK
case 30:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 45 "khroK.l"
{printf("ទ");}     
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "khroK.l"
{printf("ថ");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "khroK.l"
{printf("ឋ");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "khroK.l"
{printf("ប");} 
	YY_BREAK
case 34:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 51 "khroK.l"
{printf("ផ");}
	YY_BREAK
case 35:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 52 "khroK.l"
{printf("ភ");} 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "khroK.l"
{printf("ស");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "khroK.l"
{printf("ស់");}       
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "khroK.l"
{printf("ហ");}                  
	YY_BREAK
case 39:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 57 "khroK.l"
{printf("ឡ");}
	YY_BREAK
case 40:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 58 "khroK.l"
{printf("ល");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "khroK.l"
{printf("្ល");}
	YY_BREAK
/*'a14      {printf("្ល");} */
case 42:
YY_RULE_SETUP
#line 64 "khroK.l"
{printf("ល");}        
	YY_BREAK
/*a15              {printf("អ");}     */
case 43:
YY_RULE_SETUP
#line 69 "khroK.l"
{printf("េះ");}
	YY_BREAK
/*osoundc*/ 
case 44:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 72 "khroK.l"
{printf("គ");}
	YY_BREAK
case 45:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 73 "khroK.l"
{printf("ក");}       
	YY_BREAK
case 46:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 74 "khroK.l"
{printf("ឃ");}
	YY_BREAK
case 47:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 75 "khroK.l"
{printf("ខ");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "khroK.l"
{printf("ខ");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "khroK.l"
{printf("ង");}      
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 78 "khroK.l"
{printf("ជ");}     
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "khroK.l"
{printf("ឈ");}    
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "khroK.l"
{printf("ញ");}      
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "khroK.l"
{printf("ទ");}
	YY_BREAK
case 54:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 82 "khroK.l"
{printf("ធ");}     
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "khroK.l"
{printf("ន");}   
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "khroK.l"
{printf("ព");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "khroK.l"
{printf("ភ");}      
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "khroK.l"
{printf("ម");}    
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "khroK.l"
{printf("យ");}     
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "khroK.l"
{printf("រ");}      
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 90 "khroK.l"
{printf("វ");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 91 "khroK.l"
{printf("ឌ");}    
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 92 "khroK.l"
{printf("ឍ");}     
	YY_BREAK
/*SCcombination*/
case 64:
YY_RULE_SETUP
#line 98 "khroK.l"
{printf("ហ្គ");}     
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "khroK.l"
{printf("ហ្ន");}     
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "khroK.l"
{printf("ហ្វ");}      
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "khroK.l"
{printf("ហ្ស៊");}     
	YY_BREAK
/*SC*/
case 68:
YY_RULE_SETUP
#line 105 "khroK.l"
{printf("ឥ");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 106 "khroK.l"
{printf("ឣ");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 107 "khroK.l"
{printf("្");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 108 "khroK.l"
{printf("ៗ");}
	YY_BREAK
/*fsoundv*/
case 72:
YY_RULE_SETUP
#line 114 "khroK.l"
{printf("ឹ");} 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "khroK.l"
{printf("ឹ");}      
	YY_BREAK
/*f02               {printf("ឺ");}  */                        
case 74:
YY_RULE_SETUP
#line 117 "khroK.l"
{printf("ែ");}      
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "khroK.l"
{printf("ួ");}
	YY_BREAK
case 76:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 119 "khroK.l"
{printf("ក់");}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "khroK.l"
{printf("ៀ");}     
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "khroK.l"
{printf("ឿ");}     
	YY_BREAK
/*fsoundv*/
case 79:
YY_RULE_SETUP
#line 125 "khroK.l"
{printf("ា");}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 126 "khroK.l"
{printf("ឣ");}                          
	YY_BREAK
/*av02                {printf("ិ");}   */  
case 81:
YY_RULE_SETUP
#line 128 "khroK.l"
{printf("ី");}      
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 129 "khroK.l"
{printf("ុ");}     
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 130 "khroK.l"
{printf("ូ");}     
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 131 "khroK.l"
{printf("ើ");} 
	YY_BREAK
case 85:
/* rule 85 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
YY_LINENO_REWIND_TO(yy_bp + 4);
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 132 "khroK.l"
{printf("ើរ");}      
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 133 "khroK.l"
{printf("ី");}                
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 134 "khroK.l"
{printf("ិ");}                    
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 135 "khroK.l"
{printf("ួ");}     
	YY_BREAK
case 89:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 138 "khroK.l"
{printf("សុ");}
	YY_BREAK
/*osoundv*/
case 90:
YY_RULE_SETUP
#line 141 "khroK.l"
{printf("ឺ");}
	YY_BREAK
case 91:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 142 "khroK.l"
{printf("ើ");}
	YY_BREAK
case 92:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 143 "khroK.l"
{}
	YY_BREAK
case 93:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 144 "khroK.l"
{printf("ត់");}
	YY_BREAK
case 94:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 145 "khroK.l"
{printf("ប់");}
	YY_BREAK
case 95:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 146 "khroK.l"
{printf("ប់");}
	YY_BREAK
case 96:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 147 "khroK.l"
{printf("ន់");}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 148 "khroK.l"
{printf("ុ");}  
	YY_BREAK
case 98:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 149 "khroK.l"
{};
	YY_BREAK
case 99:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 150 "khroK.l"
{};    
	YY_BREAK
case 100:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 151 "khroK.l"
{};
	YY_BREAK
case 101:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 152 "khroK.l"
{};
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 153 "khroK.l"
{printf("ាំ");}      
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 154 "khroK.l"
{printf("ើ");}   
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 155 "khroK.l"
{printf("ា");}
	YY_BREAK
case 105:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 156 "khroK.l"
{};        
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 157 "khroK.l"
{printf("ិ");} 
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 159 "khroK.l"
{printf("ី");}  
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 160 "khroK.l"
{printf("ូ");}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 161 "khroK.l"
{printf("ូ");}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "khroK.l"
{printf("េ");}                     
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "khroK.l"
{printf("ោ");}      
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 165 "khroK.l"
{printf("ៅ");}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 166 "khroK.l"
{printf("ៅ");}       
	YY_BREAK
case 114:
*yy_cp = (yy_hold_char); /* undo effects of setting up kktext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up kktext again */
YY_RULE_SETUP
#line 167 "khroK.l"
{printf("ែ");}  
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 168 "khroK.l"
{printf("ែ");} 
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 169 "khroK.l"
{printf("ៃ");}           
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 170 "khroK.l"
{printf("ៃ");}  
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 172 "khroK.l"
{printf("ឯ");}       
	YY_BREAK
/*d*/
case 119:
YY_RULE_SETUP
#line 178 "khroK.l"
{printf("ុំ");}     
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 179 "khroK.l"
{printf("ំ");}     
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 180 "khroK.l"
{printf("ះ");}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 181 "khroK.l"
{printf("ិះ");}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 182 "khroK.l"
{printf("ុះ");}  
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 183 "khroK.l"
{printf("េះ");}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 184 "khroK.l"
{printf("េាះ");} 
	YY_BREAK
/*d*/
/*iv*/
case 126:
YY_RULE_SETUP
#line 189 "khroK.l"
{printf("ឯ");}      
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 190 "khroK.l"
{printf("ឬ");}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 191 "khroK.l"
{printf("ឱ");}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 192 "khroK.l"
{printf("ឳ");}  
	YY_BREAK
/*rules*/
case 130:
YY_RULE_SETUP
#line 198 "khroK.l"
ECHO;
	YY_BREAK
#line 1734 "khroK.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed kkin at a new source and called
			 * kklex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = kkin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( kkwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * kktext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of kklex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					kkrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			kkrestart(kkin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) kkrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 294 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 294 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 293);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up kktext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					kkrestart(kkin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( kkwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve kktext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void kkrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        kkensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            kk_create_buffer(kkin,YY_BUF_SIZE );
	}

	kk_init_buffer(YY_CURRENT_BUFFER,input_file );
	kk_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void kk_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		kkpop_buffer_state();
	 *		kkpush_buffer_state(new_buffer);
     */
	kkensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	kk_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (kkwrap()) processing, but the only time this flag
	 * is looked at is after kkwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void kk_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	kkin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE kk_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) kkalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in kk_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) kkalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in kk_create_buffer()" );

	b->yy_is_our_buffer = 1;

	kk_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with kk_create_buffer()
 * 
 */
    void kk_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		kkfree((void *) b->yy_ch_buf  );

	kkfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a kkrestart() or at EOF.
 */
    static void kk_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	kk_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then kk_init_buffer was _probably_
     * called from kkrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void kk_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		kk_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void kkpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	kkensure_buffer_stack();

	/* This block is copied from kk_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from kk_switch_to_buffer. */
	kk_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void kkpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	kk_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		kk_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void kkensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)kkalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in kkensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)kkrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in kkensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE kk_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) kkalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in kk_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	kk_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to kklex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       kk_scan_bytes() instead.
 */
YY_BUFFER_STATE kk_scan_string (yyconst char * yystr )
{
    
	return kk_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to kklex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE kk_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) kkalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in kk_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = kk_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in kk_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up kktext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		kktext[kkleng] = (yy_hold_char); \
		(yy_c_buf_p) = kktext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		kkleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int kkget_lineno  (void)
{
    
    return kklineno;
}

/** Get the input stream.
 * 
 */
FILE *kkget_in  (void)
{
        return kkin;
}

/** Get the output stream.
 * 
 */
FILE *kkget_out  (void)
{
        return kkout;
}

/** Get the length of the current token.
 * 
 */
int kkget_leng  (void)
{
        return kkleng;
}

/** Get the current token.
 * 
 */

char *kkget_text  (void)
{
        return kktext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void kkset_lineno (int  _line_number )
{
    
    kklineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see kk_switch_to_buffer
 */
void kkset_in (FILE *  _in_str )
{
        kkin = _in_str ;
}

void kkset_out (FILE *  _out_str )
{
        kkout = _out_str ;
}

int kkget_debug  (void)
{
        return kk_flex_debug;
}

void kkset_debug (int  _bdebug )
{
        kk_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from kklex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    kkin = stdin;
    kkout = stdout;
#else
    kkin = NULL;
    kkout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * kklex_init()
     */
    return 0;
}

/* kklex_destroy is for both reentrant and non-reentrant scanners. */
int kklex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		kk_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		kkpop_buffer_state();
	}

	/* Destroy the stack itself. */
	kkfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * kklex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *kkalloc (yy_size_t  size )
{
			return malloc(size);
}

void *kkrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void kkfree (void * ptr )
{
			free( (char *) ptr );	/* see kkrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 198 "khroK.l"


/*
int main () {
    kklex();
    return 0;
} */
